### ISSUE TITLE
Create Equipment Card Component

### ISSUE THREAD

**Issue by Ryan-Zhang-J3** [DSC-McMaster-U/DBAC-Companion-App#20]

**Comment by Ryan-Zhang-J3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Equipment Card Component](https://trello.com/c/8pJ3sb5m/17-create-equipment-card-component)

**Comment by mahdixmohammad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Equipment Card Component](https://trello.com/c/8pJ3sb5m/17-create-equipment-card-component)
